# Import modules

In [1]:
from moncenterlib.station_power_simulator.solar_power import SolarPanelPower
from moncenterlib.station_power_simulator.wind_turbine_power import WindTurbinePower
from moncenterlib.station_power_simulator.power_balance import PowerBalanceAnalyzer

# Wind Turbine Power Simulation

In [2]:
# Config
config_wind_turbine = {
    "latitude": 54.9874,                            # Your coordinates
    "longitude": 82.8646,                           # Your coordinates

    "start_date": "2025-01-01",                     # Date range YYYY-MM-DD
    "end_date": "2026-01-01",                       # Date range YYYY-MM-DD

    "diameter": 0.66,                               # Rotor diameter (m)
    "blade_length": 1.5,                            # Blade length (m). If you have a Vertical Axis (VAWT), set blade_length > 0. 
    # "blade_length": 0,                            # If you have a Horizontal Axis (HAWT), set blade_length = 0
    "rated_power": 450,                             # Nominal power (W)
    "rated_speed": 11,                              # Nominal wind speed (m/s)

    "cut_in": 1.3,                                  # Starting wind speed (m/s)
    "cut_out": 45,                                  # Maximum wind speed (m/s)
    
    "cp": 0.25,                                     # Aerodynamic power coefficient of rotor (Betz limit ≈ 0.59). Range 0.25 – 0.45
    "turbine_efficiency": 0.8,                      # Mechanical efficiency: gearbox, bearings, generator. Range 0.7 – 0.9
    "dc_efficiency": 1,                             # Electrical efficiency of DC conversion (controller / wiring losses). Range 0.7 – 0.95

    "timezone": "Asia/Novosibirsk",                 # Time zone of the station location (IANA format).
    # "timezone": ""                                # Leave empty ("") to detect timezone automatically from coordinates.
}


wind_power = WindTurbinePower(config_wind_turbine)      # Create object
wind_power.calculate()                                  # Start calculate

result = wind_power.get_hourly_power()                  # Return DataFrame
result

                           windspeed_10m  power
time
2025-01-01 00:00:00+07:00            2.4    1.8
2025-01-01 01:00:00+07:00            2.6    2.4
2025-01-01 02:00:00+07:00            2.7    2.6
2025-01-01 03:00:00+07:00            2.5    2.1
2025-01-01 04:00:00+07:00            2.3    1.6
...                                  ...    ...
2026-01-01 19:00:00+07:00            4.2    9.8
2026-01-01 20:00:00+07:00            3.9    7.9
2026-01-01 21:00:00+07:00            4.1    9.2
2026-01-01 22:00:00+07:00            3.7    6.7
2026-01-01 23:00:00+07:00            3.3    4.8

[8784 rows x 2 columns]

In [ ]:
all_period_metrics_df = wind_power.get_all_period_metrics()
all_period_metrics_df = wind_power.get_all_period_metrics(path_protocol="all_period.txt")  # Save report to file.
all_period_metrics_df                                                                      # Contains the same metrics as printed in the console.

monthly_metrics_df = wind_power.get_monthly_metrics()
monthly_metrics_df = wind_power.get_monthly_metrics(step=3)                                # Number of months per period (e.g., 3 = quarterly).
monthly_metrics_df = wind_power.get_monthly_metrics(path_protocol="monthly_period.txt")    # Save report to file.
monthly_metrics_df                                                                         # Contains the same metrics as printed in the console.

seasonal_metrics_df = wind_power.get_seasonal_metrics()
seasonal_metrics_df = wind_power.get_seasonal_metrics(path_protocol="seasonal_period.txt") # Save report to file.
seasonal_metrics_df                                                                        # Contains the same metrics as printed in the console.

# Solar Power Simulation

In [4]:
config_solar_panel = {
    "latitude": 54.9874,                                # Your coordinates
    "longitude": 82.8646,                               # Your coordinates

    "start_date": "2025-01-01",                         # Date range YYYY-MM-DD
    "end_date": "2026-01-01",                           # Date range YYYY-MM-DD
    
    "tilt_deg": 90,                                     # Tilt angle of the solar panel from horizontal (degrees). Range 0-90
    "panel_azimuth_deg": 180,                           # Panel azimuth: 180° = south, 90° = east, 270° = west, 0° = north.

    "area_m2": 0.627,                                   # Total panel area (m²).
    "panel_efficiency": 0.1923,                         # Module conversion efficiency
    "dc_efficiency": 1,                                 # Electrical efficiency of DC system (controller, wiring).

    "timezone": "Asia/Novosibirsk",                     # Time zone of the station location (IANA format).
    # "timezone": ""                                    # Leave empty ("") to detect timezone automatically from coordinates.
}

solar_power = SolarPanelPower(config_solar_panel)       # Create object
solar_power.calculate()                                 # Start calculate

solar_power.get_hourly_power()                          # Return DataFrame

,shortwave_radiation,temperature_2m,snowfall,precipitation,sunrise,sunset,sun_duration,power
time,,,,,,,,
2025-01-01 00:00:00+07:00,0.0,-11.8,0.00,0.0,2025-01-01 09:53:00,2025-01-01 17:11:00,7.30,0.0
2025-01-01 01:00:00+07:00,0.0,-11.9,0.00,0.0,2025-01-01 09:53:00,2025-01-01 17:11:00,7.30,0.0
2025-01-01 02:00:00+07:00,0.0,-12.2,0.00,0.0,2025-01-01 09:53:00,2025-01-01 17:11:00,7.30,0.0
2025-01-01 03:00:00+07:00,0.0,-12.6,0.00,0.0,2025-01-01 09:53:00,2025-01-01 17:11:00,7.30,0.0
2025-01-01 04:00:00+07:00,0.0,-12.9,0.00,0.0,2025-01-01 09:53:00,2025-01-01 17:11:00,7.30,0.0
...,...,...,...,...,...,...,...,...
2026-01-01 19:00:00+07:00,0.0,-9.4,0.07,0.1,2026-01-01 09:53:00,2026-01-01 17:10:00,7.28,0.0
2026-01-01 20:00:00+07:00,0.0,-9.8,0.07,0.1,2026-01-01 09:53:00,2026-01-01 17:10:00,7.28,0.0
2026-01-01 21:00:00+07:00,0.0,-9.8,0.00,0.0,2026-01-01 09:53:00,2026-01-01 17:10:00,7.28,0.0
2026-01-01 22:00:00+07:00,0.0,-9.8,0.00,0.0,2026-01-01 09:53:00,2026-01-01 17:10:00,7.28,0.0
2026-01-01 23:00:00+07:00,0.0,-9.6,0.00,0.0,2026-01-01 09:53:00,2026-01-01 17:10:00,7.28,0.0

In [ ]:
all_period_metrics_df = solar_power.get_all_period_metrics()
all_period_metrics_df = solar_power.get_all_period_metrics(path_protocol="all_period.txt")  # Save report to file.
all_period_metrics_df                                                                       # Contains the same metrics as printed in the console.

monthly_metrics_df = solar_power.get_monthly_metrics()
monthly_metrics_df = solar_power.get_monthly_metrics(path_protocol="monthly_period.txt")    # Save report to file.
monthly_metrics_df                                                                          # Contains the same metrics as printed in the console.

seasonal_metrics_df = solar_power.get_seasonal_metrics()
seasonal_metrics_df = solar_power.get_seasonal_metrics(path_protocol="seasonal_period.txt") # Save report to file.
seasonal_metrics_df                                                                         # Contains the same metrics as printed in the console.

# Power Balance Analyzer

## Create solar and wind turbine dataframes

In [2]:
start_date = "2025-01-01"
end_date = "2026-01-01"

latitude = 54.9874                                
longitude = 82.8646

timezone = "Asia/Novosibirsk"

config_solar_panel_135 = {
    "latitude": latitude,                               # Your coordinates
    "longitude": longitude,                             # Your coordinates

    "start_date": start_date,                           # Date range YYYY-MM-DD
    "end_date": end_date,                               # Date range YYYY-MM-DD
    
    "tilt_deg": 90,                                     # Tilt angle of the solar panel from horizontal (degrees). Range 0-90
    "panel_azimuth_deg": 135,                           # Panel azimuth: 180° = south, 90° = east, 270° = west, 0° = north.

    "area_m2": 0.627,                                   # Total panel area (m²).
    "panel_efficiency": 0.1923,                         # Module conversion efficiency
    "dc_efficiency": 1,                                 # Electrical efficiency of DC system (controller, wiring).

    "timezone": timezone,                               # Time zone of the station location (IANA format).
    # "timezone": ""                                    # Leave empty ("") to detect timezone automatically from coordinates.
}

config_solar_panel_225 = {
    "latitude": latitude,                               # Your coordinates
    "longitude": longitude,                             # Your coordinates

    "start_date": start_date,                           # Date range YYYY-MM-DD
    "end_date": end_date,                               # Date range YYYY-MM-DD
    
    "tilt_deg": 90,                                     # Tilt angle of the solar panel from horizontal (degrees). Range 0-90
    "panel_azimuth_deg": 225,                           # Panel azimuth: 180° = south, 90° = east, 270° = west, 0° = north.

    "area_m2": 0.627,                                   # Total panel area (m²).
    "panel_efficiency": 0.1923,                         # Module conversion efficiency
    "dc_efficiency": 1,                                 # Electrical efficiency of DC system (controller, wiring).

    "timezone": timezone,                               # Time zone of the station location (IANA format).
    # "timezone": ""                                    # Leave empty ("") to detect timezone automatically from coordinates.
}

config_wind_turbine = {
    "latitude": latitude,                               # Your coordinates
    "longitude": longitude,                             # Your coordinates

    "start_date": start_date,                           # Date range YYYY-MM-DD
    "end_date": end_date,                               # Date range YYYY-MM-DD

    "diameter": 0.66,                                   # Rotor diameter (m)
    "blade_length": 1.5,                                # Blade length (m). If you have a Vertical Axis (VAWT), set blade_length > 0. 
    # "blade_length": 0,                                # If you have a Horizontal Axis (HAWT), set blade_length = 0
    "rated_power": 450,                                 # Nominal power (W)
    "rated_speed": 11,                                  # Nominal wind speed (m/s)

    "cut_in": 1.3,                                      # Starting wind speed (m/s)
    "cut_out": 45,                                      # Maximum wind speed (m/s)
    
    "cp": 0.25,                                         # Aerodynamic power coefficient of rotor (Betz limit ≈ 0.59). Range 0.25 – 0.45
    "turbine_efficiency": 0.8,                          # Mechanical efficiency: gearbox, bearings, generator. Range 0.7 – 0.9
    "dc_efficiency": 1,                                 # Electrical efficiency of DC conversion (controller / wiring losses). Range 0.7 – 0.95

    "timezone": timezone,                               # Time zone of the station location (IANA format).
    # "timezone": ""                                    # Leave empty ("") to detect timezone automatically from coordinates.
}

solar_power_135 = SolarPanelPower(config_solar_panel_135)       # Create object
solar_power_135.calculate()                                     # Start calculate

solar_power_225 = SolarPanelPower(config_solar_panel_225)       # Create object
solar_power_225.calculate()                                     # Start calculate

wind_turbine = WindTurbinePower(config_wind_turbine)            # Create object
wind_turbine.calculate()                                        # Start calculate

In [3]:
power_balance = PowerBalanceAnalyzer()                                                              # Create object
df_station = power_balance.combine_power([solar_power_135, solar_power_225, wind_turbine])          # combine powers
df_station

                           power
time
2025-01-01 00:00:00+07:00    1.8
2025-01-01 01:00:00+07:00    2.4
2025-01-01 02:00:00+07:00    2.6
2025-01-01 03:00:00+07:00    2.1
2025-01-01 04:00:00+07:00    1.6
...                          ...
2026-01-01 19:00:00+07:00    9.8
2026-01-01 20:00:00+07:00    7.9
2026-01-01 21:00:00+07:00    9.2
2026-01-01 22:00:00+07:00    6.7
2026-01-01 23:00:00+07:00    4.8

[8784 rows x 1 columns]

In [4]:
power_load = 1.5 # Watt 
df, metrics = power_balance.calc_power_balance(df_station, power_load, path_protocol="power_balance_with_load.txt")   # power balance with load

==============================
Период: 2025-01-01 — 2026-01-01
Мощность нагрузки: 1.5 Вт
Покрыто часов: 7410 из 8784 (84.36%)
Потребление нагрузки: 13176.0 Вт·ч
Генерация станции: 325535.1 Вт·ч
Излишек генерации: 313691.0 Вт·ч
Дефицит: 1331.9 Вт·ч
Средний дефицит (в часы дефицита): 1.0 Вт

In [6]:
df_sim, metrics = power_balance.calc_power_balance_with_battery(                # power balance with load + battery
    input_df=df_station,            # DataFrame returned by combine_power()
    load_power_w=10.5,               # Constant load power (W)
    battery_capacity_Wh=35,         # Battery capacity (Wh)
    initial_soc_Wh=35,              # Initial battery state of charge (Wh)
    charge_efficiency=0.85,         # Battery charging efficiency
    discharge_efficiency=0.85,      # Battery discharging efficiency
    min_soc_Wh=5,                    # minimum battery state of charge (Wh)
    path_protocol = "power_balance_with_load_battery.txt"
)  


df_sim              # Simulation time-series DataFrame
metrics             # Summary metrics of the simulation
metrics["events"]   # List of timestamps when the system turned off/on

==============================
Период: 2025-01-01 — 2026-01-01
Нагрузка: 10.5 Вт
Ёмкость аккумулятора: 35.0 Вт·ч
Начальный заряд АКБ: 35.0 Вт·ч
Конечный заряд АКБ: 18.41 Вт·ч
Система работала: 6219 из 8784 часов (70.8%)
Суммарная генерация: 325535.1 Вт·ч
Суммарная нагрузка: 92232.0 Вт·ч
Вывод: были отключения. Первый момент отключения: 2025-01-01 03:00:00+07:00

Интервалы отключений:
1. Выключение: 2025-01-01 03:00:00+07:00, включение: 2025-01-01 12:00:00+07:00, длительность: 9 ч
2. Выключение: 2025-01-01 22:00:00+07:00, включение: 2025-01-02 00:00:00+07:00, длительность: 2 ч
3. Выключение: 2025-01-02 01:00:00+07:00, включение: 2025-01-02 06:00:00+07:00, длительность: 5 ч
4. Выключение: 2025-01-05 06:00:00+07:00, включение: 2025-01-05 12:00:00+07:00, длительность: 6 ч
5. Выключение: 2025-01-05 20:00:00+07:00, включение: 2025-01-06 11:00:00+07:00, длительность: 15 ч
6. Выключение: 2025-01-06 22:00:00+07:00, включение: 2025-01-07 12:00:00+07:00, длительность: 14 ч
7. Выключение: 2025-01-07 20:00:00+07:00, включение: 2025-01-08 13:00:00+07:00, длительность: 17 ч
8. Выключение: 2025-01-09 05:00:00+07:00, включение: 2025-01-09 11:00:00+07:00, длительность: 6 ч
9. Выключение: 2025-01-09 23:00:00+07:00, включение: 2025-01-10 09:00:00+07:00, длительность: 10 ч
10. Выключение: 2025-01-12 10:00:00+07:00, включение: 2025-01-12 12:00:00+07:00, длительность: 2 ч
11. Выключение: 2025-01-12 20:00:00+07:00, включение: 2025-01-13 12:00:00+07:00, длительность: 16 ч
12. Выключение: 2025-01-14 23:00:00+07:00, включение: 2025-01-15 08:00:00+07:00, длительность: 9 ч
13. Выключение: 2025-01-17 21:00:00+07:00, включение: 2025-01-18 08:00:00+07:00, длительность: 11 ч
14. Выключение: 2025-01-19 02:00:00+07:00, включение: 2025-01-19 04:00:00+07:00, длительность: 2 ч
15. Выключение: 2025-01-19 09:00:00+07:00, включение: 2025-01-19 11:00:00+07:00, длительность: 2 ч
16. Выключение: 2025-01-24 06:00:00+07:00, включение: 2025-01-24 11:00:00+07:00, длительность: 5 ч
17. Выключение: 2025-01-26 06:00:00+07:00, включение: 2025-01-26 11:00:00+07:00, длительность: 5 ч
18. Выключение: 2025-01-26 21:00:00+07:00, включение: 2025-01-27 11:00:00+07:00, длительность: 14 ч
19. Выключение: 2025-01-27 22:00:00+07:00, включение: 2025-01-28 11:00:00+07:00, длительность: 13 ч
20. Выключение: 2025-01-28 23:00:00+07:00, включение: 2025-01-29 11:00:00+07:00, длительность: 12 ч
21. Выключение: 2025-01-29 20:00:00+07:00, включение: 2025-01-30 11:00:00+07:00, длительность: 15 ч
22. Выключение: 2025-01-30 21:00:00+07:00, включение: 2025-01-31 11:00:00+07:00, длительность: 14 ч
23. Выключение: 2025-01-31 20:00:00+07:00, включение: 2025-02-01 11:00:00+07:00, длительность: 15 ч
24. Выключение: 2025-02-01 23:00:00+07:00, включение: 2025-02-02 10:00:00+07:00, длительность: 11 ч
25. Выключение: 2025-02-02 21:00:00+07:00, включение: 2025-02-03 11:00:00+07:00, длительность: 14 ч
26. Выключение: 2025-02-03 23:00:00+07:00, включение: 2025-02-04 11:00:00+07:00, длительность: 12 ч
27. Выключение: 2025-02-04 21:00:00+07:00, включение: 2025-02-05 11:00:00+07:00, длительность: 14 ч
28. Выключение: 2025-02-05 23:00:00+07:00, включение: 2025-02-06 11:00:00+07:00, длительность: 12 ч
29. Выключение: 2025-02-07 05:00:00+07:00, включение: 2025-02-07 11:00:00+07:00, длительность: 6 ч
30. Выключение: 2025-02-07 22:00:00+07:00, включение: 2025-02-08 11:00:00+07:00, длительность: 13 ч
31. Выключение: 2025-02-14 22:00:00+07:00, включение: 2025-02-15 10:00:00+07:00, длительность: 12 ч
32. Выключение: 2025-02-15 22:00:00+07:00, включение: 2025-02-16 11:00:00+07:00, длительность: 13 ч
33. Выключение: 2025-02-16 21:00:00+07:00, включение: 2025-02-17 11:00:00+07:00, длительность: 14 ч
34. Выключение: 2025-02-17 21:00:00+07:00, включение: 2025-02-18 10:00:00+07:00, длительность: 13 ч
35. Выключение: 2025-02-18 21:00:00+07:00, включение: 2025-02-19 10:00:00+07:00, длительность: 13 ч
36. Выключение: 2025-02-19 21:00:00+07:00, включение: 2025-02-20 10:00:00+07:00, длительность: 13 ч
37. Выключение: 2025-02-20 22:00:00+07:00, включение: 2025-02-21 09:00:00+07:00, длительность: 11 ч
38. Выключение: 2025-02-21 21:00:00+07:00, включение: 2025-02-22 10:00:00+07:00, длительность: 13 ч
39. Выключение: 2025-02-22 21:00:00+07:00, включение: 2025-02-23 10:00:00+07:00, длительность: 13 ч
40. Выключение: 2025-02-23 21:00:00+07:00, включение: 2025-02-24 10:00:00+07:00, длительность: 13 ч
41. Выключение: 2025-02-24 21:00:00+07:00, включение: 2025-02-25 10:00:00+07:00, длительность: 13 ч
42. Выключение: 2025-02-25 21:00:00+07:00, включение: 2025-02-26 10:00:00+07:00, длительность: 13 ч
43. Выключение: 2025-02-26 22:00:00+07:00, включение: 2025-02-27 11:00:00+07:00, длительность: 13 ч
44. Выключение: 2025-02-27 21:00:00+07:00, включение: 2025-02-28 10:00:00+07:00, длительность: 13 ч
45. Выключение: 2025-02-28 21:00:00+07:00, включение: 2025-03-01 10:00:00+07:00, длительность: 13 ч
46. Выключение: 2025-03-01 23:00:00+07:00, включение: 2025-03-02 10:00:00+07:00, длительность: 11 ч
47. Выключение: 2025-03-02 23:00:00+07:00, включение: 2025-03-03 10:00:00+07:00, длительность: 11 ч
48. Выключение: 2025-03-03 22:00:00+07:00, включение: 2025-03-04 10:00:00+07:00, длительность: 12 ч
49. Выключение: 2025-03-05 07:00:00+07:00, включение: 2025-03-05 10:00:00+07:00, длительность: 3 ч
50. Выключение: 2025-03-06 08:00:00+07:00, включение: 2025-03-06 09:00:00+07:00, длительность: 1 ч
51. Выключение: 2025-03-08 23:00:00+07:00, включение: 2025-03-09 10:00:00+07:00, длительность: 11 ч
52. Выключение: 2025-03-09 23:00:00+07:00, включение: 2025-03-10 09:00:00+07:00, длительность: 10 ч
53. Выключение: 2025-03-11 05:00:00+07:00, включение: 2025-03-11 10:00:00+07:00, длительность: 5 ч
54. Выключение: 2025-03-11 23:00:00+07:00, включение: 2025-03-12 09:00:00+07:00, длительность: 10 ч
55. Выключение: 2025-03-12 22:00:00+07:00, включение: 2025-03-13 09:00:00+07:00, длительность: 11 ч
56. Выключение: 2025-03-15 05:00:00+07:00, включение: 2025-03-15 09:00:00+07:00, длительность: 4 ч
57. Выключение: 2025-03-16 03:00:00+07:00, включение: 2025-03-16 09:00:00+07:00, длительность: 6 ч
58. Выключение: 2025-03-21 07:00:00+07:00, включение: 2025-03-21 09:00:00+07:00, длительность: 2 ч
59. Выключение: 2025-03-22 23:00:00+07:00, включение: 2025-03-23 09:00:00+07:00, длительность: 10 ч
60. Выключение: 2025-03-25 23:00:00+07:00, включение: 2025-03-26 09:00:00+07:00, длительность: 10 ч
61. Выключение: 2025-03-26 23:00:00+07:00, включение: 2025-03-27 09:00:00+07:00, длительность: 10 ч
62. Выключение: 2025-03-28 00:00:00+07:00, включение: 2025-03-28 09:00:00+07:00, длительность: 9 ч
63. Выключение: 2025-03-28 23:00:00+07:00, включение: 2025-03-29 09:00:00+07:00, длительность: 10 ч
64. Выключение: 2025-03-29 23:00:00+07:00, включение: 2025-03-30 09:00:00+07:00, длительность: 10 ч
65. Выключение: 2025-03-31 01:00:00+07:00, включение: 2025-03-31 09:00:00+07:00, длительность: 8 ч
66. Выключение: 2025-04-01 01:00:00+07:00, включение: 2025-04-01 09:00:00+07:00, длительность: 8 ч
67. Выключение: 2025-04-02 07:00:00+07:00, включение: 2025-04-02 09:00:00+07:00, длительность: 2 ч
68. Выключение: 2025-04-02 23:00:00+07:00, включение: 2025-04-03 07:00:00+07:00, длительность: 8 ч
69. Выключение: 2025-04-06 23:00:00+07:00, включение: 2025-04-07 09:00:00+07:00, длительность: 10 ч
70. Выключение: 2025-04-08 01:00:00+07:00, включение: 2025-04-08 08:00:00+07:00, длительность: 7 ч
71. Выключение: 2025-04-09 04:00:00+07:00, включение: 2025-04-09 08:00:00+07:00, длительность: 4 ч
72. Выключение: 2025-04-10 01:00:00+07:00, включение: 2025-04-10 08:00:00+07:00, длительность: 7 ч
73. Выключение: 2025-04-13 03:00:00+07:00, включение: 2025-04-13 08:00:00+07:00, длительность: 5 ч
74. Выключение: 2025-04-14 00:00:00+07:00, включение: 2025-04-14 08:00:00+07:00, длительность: 8 ч
75. Выключение: 2025-04-15 02:00:00+07:00, включение: 2025-04-15 08:00:00+07:00, длительность: 6 ч
76. Выключение: 2025-04-15 23:00:00+07:00, включение: 2025-04-16 08:00:00+07:00, длительность: 9 ч
77. Выключение: 2025-04-19 00:00:00+07:00, включение: 2025-04-19 05:00:00+07:00, длительность: 5 ч
78. Выключение: 2025-04-19 06:00:00+07:00, включение: 2025-04-19 07:00:00+07:00, длительность: 1 ч
79. Выключение: 2025-04-19 23:00:00+07:00, включение: 2025-04-20 07:00:00+07:00, длительность: 8 ч
80. Выключение: 2025-04-21 05:00:00+07:00, включение: 2025-04-21 08:00:00+07:00, длительность: 3 ч
81. Выключение: 2025-04-21 23:00:00+07:00, включение: 2025-04-22 08:00:00+07:00, длительность: 9 ч
82. Выключение: 2025-04-23 00:00:00+07:00, включение: 2025-04-23 07:00:00+07:00, длительность: 7 ч
83. Выключение: 2025-04-24 04:00:00+07:00, включение: 2025-04-24 08:00:00+07:00, длительность: 4 ч
84. Выключение: 2025-04-24 23:00:00+07:00, включение: 2025-04-25 08:00:00+07:00, длительность: 9 ч
85. Выключение: 2025-04-26 01:00:00+07:00, включение: 2025-04-26 07:00:00+07:00, длительность: 6 ч
86. Выключение: 2025-04-27 22:00:00+07:00, включение: 2025-04-28 08:00:00+07:00, длительность: 10 ч
87. Выключение: 2025-04-29 00:00:00+07:00, включение: 2025-04-29 07:00:00+07:00, длительность: 7 ч
88. Выключение: 2025-04-30 23:00:00+07:00, включение: 2025-05-01 08:00:00+07:00, длительность: 9 ч
89. Выключение: 2025-05-01 23:00:00+07:00, включение: 2025-05-02 08:00:00+07:00, длительность: 9 ч
90. Выключение: 2025-05-02 23:00:00+07:00, включение: 2025-05-03 03:00:00+07:00, длительность: 4 ч
91. Выключение: 2025-05-04 00:00:00+07:00, включение: 2025-05-04 08:00:00+07:00, длительность: 8 ч
92. Выключение: 2025-05-06 00:00:00+07:00, включение: 2025-05-06 07:00:00+07:00, длительность: 7 ч
93. Выключение: 2025-05-07 00:00:00+07:00, включение: 2025-05-07 07:00:00+07:00, длительность: 7 ч
94. Выключение: 2025-05-08 03:00:00+07:00, включение: 2025-05-08 09:00:00+07:00, длительность: 6 ч
95. Выключение: 2025-05-09 00:00:00+07:00, включение: 2025-05-09 08:00:00+07:00, длительность: 8 ч
96. Выключение: 2025-05-10 01:00:00+07:00, включение: 2025-05-10 08:00:00+07:00, длительность: 7 ч
97. Выключение: 2025-05-11 04:00:00+07:00, включение: 2025-05-11 09:00:00+07:00, длительность: 5 ч
98. Выключение: 2025-05-12 01:00:00+07:00, включение: 2025-05-12 07:00:00+07:00, длительность: 6 ч
99. Выключение: 2025-05-13 00:00:00+07:00, включение: 2025-05-13 09:00:00+07:00, длительность: 9 ч
100. Выключение: 2025-05-14 00:00:00+07:00, включение: 2025-05-14 07:00:00+07:00, длительность: 7 ч
101. Выключение: 2025-05-15 03:00:00+07:00, включение: 2025-05-15 07:00:00+07:00, длительность: 4 ч
102. Выключение: 2025-05-16 01:00:00+07:00, включение: 2025-05-16 09:00:00+07:00, длительность: 8 ч
103. Выключение: 2025-05-17 00:00:00+07:00, включение: 2025-05-17 07:00:00+07:00, длительность: 7 ч
104. Выключение: 2025-05-18 00:00:00+07:00, включение: 2025-05-18 07:00:00+07:00, длительность: 7 ч
105. Выключение: 2025-05-19 03:00:00+07:00, включение: 2025-05-19 07:00:00+07:00, длительность: 4 ч
106. Выключение: 2025-05-20 00:00:00+07:00, включение: 2025-05-20 08:00:00+07:00, длительность: 8 ч
107. Выключение: 2025-05-21 02:00:00+07:00, включение: 2025-05-21 07:00:00+07:00, длительность: 5 ч
108. Выключение: 2025-05-22 03:00:00+07:00, включение: 2025-05-22 07:00:00+07:00, длительность: 4 ч
109. Выключение: 2025-05-23 00:00:00+07:00, включение: 2025-05-23 07:00:00+07:00, длительность: 7 ч
110. Выключение: 2025-05-24 01:00:00+07:00, включение: 2025-05-24 07:00:00+07:00, длительность: 6 ч
111. Выключение: 2025-05-25 03:00:00+07:00, включение: 2025-05-25 07:00:00+07:00, длительность: 4 ч
112. Выключение: 2025-05-26 01:00:00+07:00, включение: 2025-05-26 07:00:00+07:00, длительность: 6 ч
113. Выключение: 2025-05-27 04:00:00+07:00, включение: 2025-05-27 07:00:00+07:00, длительность: 3 ч
114. Выключение: 2025-05-28 00:00:00+07:00, включение: 2025-05-28 08:00:00+07:00, длительность: 8 ч
115. Выключение: 2025-05-29 01:00:00+07:00, включение: 2025-05-29 07:00:00+07:00, длительность: 6 ч
116. Выключение: 2025-05-30 00:00:00+07:00, включение: 2025-05-30 07:00:00+07:00, длительность: 7 ч
117. Выключение: 2025-05-31 02:00:00+07:00, включение: 2025-05-31 07:00:00+07:00, длительность: 5 ч
118. Выключение: 2025-06-01 00:00:00+07:00, включение: 2025-06-01 07:00:00+07:00, длительность: 7 ч
119. Выключение: 2025-06-02 00:00:00+07:00, включение: 2025-06-02 07:00:00+07:00, длительность: 7 ч
120. Выключение: 2025-06-03 00:00:00+07:00, включение: 2025-06-03 07:00:00+07:00, длительность: 7 ч
121. Выключение: 2025-06-04 00:00:00+07:00, включение: 2025-06-04 07:00:00+07:00, длительность: 7 ч
122. Выключение: 2025-06-05 01:00:00+07:00, включение: 2025-06-05 07:00:00+07:00, длительность: 6 ч
123. Выключение: 2025-06-06 01:00:00+07:00, включение: 2025-06-06 07:00:00+07:00, длительность: 6 ч
124. Выключение: 2025-06-07 00:00:00+07:00, включение: 2025-06-07 07:00:00+07:00, длительность: 7 ч
125. Выключение: 2025-06-08 03:00:00+07:00, включение: 2025-06-08 10:00:00+07:00, длительность: 7 ч
126. Выключение: 2025-06-09 00:00:00+07:00, включение: 2025-06-09 07:00:00+07:00, длительность: 7 ч
127. Выключение: 2025-06-10 00:00:00+07:00, включение: 2025-06-10 07:00:00+07:00, длительность: 7 ч
128. Выключение: 2025-06-11 00:00:00+07:00, включение: 2025-06-11 07:00:00+07:00, длительность: 7 ч
129. Выключение: 2025-06-12 00:00:00+07:00, включение: 2025-06-12 07:00:00+07:00, длительность: 7 ч
130. Выключение: 2025-06-13 00:00:00+07:00, включение: 2025-06-13 07:00:00+07:00, длительность: 7 ч
131. Выключение: 2025-06-14 00:00:00+07:00, включение: 2025-06-14 07:00:00+07:00, длительность: 7 ч
132. Выключение: 2025-06-15 01:00:00+07:00, включение: 2025-06-15 07:00:00+07:00, длительность: 6 ч
133. Выключение: 2025-06-16 00:00:00+07:00, включение: 2025-06-16 07:00:00+07:00, длительность: 7 ч
134. Выключение: 2025-06-17 00:00:00+07:00, включение: 2025-06-17 07:00:00+07:00, длительность: 7 ч
135. Выключение: 2025-06-18 00:00:00+07:00, включение: 2025-06-18 07:00:00+07:00, длительность: 7 ч
136. Выключение: 2025-06-19 00:00:00+07:00, включение: 2025-06-19 07:00:00+07:00, длительность: 7 ч
137. Выключение: 2025-06-21 04:00:00+07:00, включение: 2025-06-21 07:00:00+07:00, длительность: 3 ч
138. Выключение: 2025-06-23 05:00:00+07:00, включение: 2025-06-23 07:00:00+07:00, длительность: 2 ч
139. Выключение: 2025-06-24 01:00:00+07:00, включение: 2025-06-24 07:00:00+07:00, длительность: 6 ч
140. Выключение: 2025-06-25 01:00:00+07:00, включение: 2025-06-25 07:00:00+07:00, длительность: 6 ч
141. Выключение: 2025-06-26 01:00:00+07:00, включение: 2025-06-26 07:00:00+07:00, длительность: 6 ч
142. Выключение: 2025-06-27 01:00:00+07:00, включение: 2025-06-27 07:00:00+07:00, длительность: 6 ч
143. Выключение: 2025-06-28 04:00:00+07:00, включение: 2025-06-28 07:00:00+07:00, длительность: 3 ч
144. Выключение: 2025-06-29 00:00:00+07:00, включение: 2025-06-29 07:00:00+07:00, длительность: 7 ч
145. Выключение: 2025-06-30 01:00:00+07:00, включение: 2025-06-30 07:00:00+07:00, длительность: 6 ч
146. Выключение: 2025-07-01 00:00:00+07:00, включение: 2025-07-01 07:00:00+07:00, длительность: 7 ч
147. Выключение: 2025-07-02 00:00:00+07:00, включение: 2025-07-02 07:00:00+07:00, длительность: 7 ч
148. Выключение: 2025-07-03 00:00:00+07:00, включение: 2025-07-03 07:00:00+07:00, длительность: 7 ч
149. Выключение: 2025-07-04 00:00:00+07:00, включение: 2025-07-04 07:00:00+07:00, длительность: 7 ч
150. Выключение: 2025-07-05 02:00:00+07:00, включение: 2025-07-05 07:00:00+07:00, длительность: 5 ч
151. Выключение: 2025-07-06 01:00:00+07:00, включение: 2025-07-06 08:00:00+07:00, длительность: 7 ч
152. Выключение: 2025-07-07 01:00:00+07:00, включение: 2025-07-07 07:00:00+07:00, длительность: 6 ч
153. Выключение: 2025-07-08 00:00:00+07:00, включение: 2025-07-08 08:00:00+07:00, длительность: 8 ч
154. Выключение: 2025-07-09 00:00:00+07:00, включение: 2025-07-09 07:00:00+07:00, длительность: 7 ч
155. Выключение: 2025-07-10 00:00:00+07:00, включение: 2025-07-10 07:00:00+07:00, длительность: 7 ч
156. Выключение: 2025-07-11 00:00:00+07:00, включение: 2025-07-11 07:00:00+07:00, длительность: 7 ч
157. Выключение: 2025-07-12 00:00:00+07:00, включение: 2025-07-12 07:00:00+07:00, длительность: 7 ч
158. Выключение: 2025-07-13 03:00:00+07:00, включение: 2025-07-13 06:00:00+07:00, длительность: 3 ч
159. Выключение: 2025-07-14 01:00:00+07:00, включение: 2025-07-14 07:00:00+07:00, длительность: 6 ч
160. Выключение: 2025-07-15 00:00:00+07:00, включение: 2025-07-15 07:00:00+07:00, длительность: 7 ч
161. Выключение: 2025-07-16 00:00:00+07:00, включение: 2025-07-16 08:00:00+07:00, длительность: 8 ч
162. Выключение: 2025-07-17 01:00:00+07:00, включение: 2025-07-17 07:00:00+07:00, длительность: 6 ч
163. Выключение: 2025-07-18 00:00:00+07:00, включение: 2025-07-18 07:00:00+07:00, длительность: 7 ч
164. Выключение: 2025-07-19 00:00:00+07:00, включение: 2025-07-19 08:00:00+07:00, длительность: 8 ч
165. Выключение: 2025-07-21 02:00:00+07:00, включение: 2025-07-21 09:00:00+07:00, длительность: 7 ч
166. Выключение: 2025-07-22 00:00:00+07:00, включение: 2025-07-22 08:00:00+07:00, длительность: 8 ч
167. Выключение: 2025-07-23 00:00:00+07:00, включение: 2025-07-23 07:00:00+07:00, длительность: 7 ч
168. Выключение: 2025-07-24 01:00:00+07:00, включение: 2025-07-24 07:00:00+07:00, длительность: 6 ч
169. Выключение: 2025-07-25 01:00:00+07:00, включение: 2025-07-25 07:00:00+07:00, длительность: 6 ч
170. Выключение: 2025-07-26 01:00:00+07:00, включение: 2025-07-26 07:00:00+07:00, длительность: 6 ч
171. Выключение: 2025-07-28 06:00:00+07:00, включение: 2025-07-28 07:00:00+07:00, длительность: 1 ч
172. Выключение: 2025-07-29 01:00:00+07:00, включение: 2025-07-29 08:00:00+07:00, длительность: 7 ч
173. Выключение: 2025-07-30 00:00:00+07:00, включение: 2025-07-30 08:00:00+07:00, длительность: 8 ч
174. Выключение: 2025-07-31 00:00:00+07:00, включение: 2025-07-31 07:00:00+07:00, длительность: 7 ч
175. Выключение: 2025-08-01 00:00:00+07:00, включение: 2025-08-01 08:00:00+07:00, длительность: 8 ч
176. Выключение: 2025-08-02 00:00:00+07:00, включение: 2025-08-02 08:00:00+07:00, длительность: 8 ч
177. Выключение: 2025-08-04 00:00:00+07:00, включение: 2025-08-04 08:00:00+07:00, длительность: 8 ч
178. Выключение: 2025-08-05 00:00:00+07:00, включение: 2025-08-05 08:00:00+07:00, длительность: 8 ч
179. Выключение: 2025-08-06 00:00:00+07:00, включение: 2025-08-06 08:00:00+07:00, длительность: 8 ч
180. Выключение: 2025-08-07 03:00:00+07:00, включение: 2025-08-07 08:00:00+07:00, длительность: 5 ч
181. Выключение: 2025-08-07 23:00:00+07:00, включение: 2025-08-08 08:00:00+07:00, длительность: 9 ч
182. Выключение: 2025-08-09 00:00:00+07:00, включение: 2025-08-09 09:00:00+07:00, длительность: 9 ч
183. Выключение: 2025-08-10 00:00:00+07:00, включение: 2025-08-10 08:00:00+07:00, длительность: 8 ч
184. Выключение: 2025-08-11 00:00:00+07:00, включение: 2025-08-11 08:00:00+07:00, длительность: 8 ч
185. Выключение: 2025-08-12 00:00:00+07:00, включение: 2025-08-12 08:00:00+07:00, длительность: 8 ч
186. Выключение: 2025-08-12 23:00:00+07:00, включение: 2025-08-13 08:00:00+07:00, длительность: 9 ч
187. Выключение: 2025-08-13 23:00:00+07:00, включение: 2025-08-14 08:00:00+07:00, длительность: 9 ч
188. Выключение: 2025-08-16 00:00:00+07:00, включение: 2025-08-16 01:00:00+07:00, длительность: 1 ч
189. Выключение: 2025-08-16 02:00:00+07:00, включение: 2025-08-16 08:00:00+07:00, длительность: 6 ч
190. Выключение: 2025-08-17 00:00:00+07:00, включение: 2025-08-17 08:00:00+07:00, длительность: 8 ч
191. Выключение: 2025-08-18 00:00:00+07:00, включение: 2025-08-18 08:00:00+07:00, длительность: 8 ч
192. Выключение: 2025-08-19 00:00:00+07:00, включение: 2025-08-19 08:00:00+07:00, длительность: 8 ч
193. Выключение: 2025-08-19 23:00:00+07:00, включение: 2025-08-20 08:00:00+07:00, длительность: 9 ч
194. Выключение: 2025-08-20 23:00:00+07:00, включение: 2025-08-21 08:00:00+07:00, длительность: 9 ч
195. Выключение: 2025-08-22 00:00:00+07:00, включение: 2025-08-22 08:00:00+07:00, длительность: 8 ч
196. Выключение: 2025-08-23 03:00:00+07:00, включение: 2025-08-23 08:00:00+07:00, длительность: 5 ч

                shutdown_time              restore_time  duration_hours
0   2025-01-01 03:00:00+07:00 2025-01-01 12:00:00+07:00               9
1   2025-01-01 22:00:00+07:00 2025-01-02 00:00:00+07:00               2
2   2025-01-02 01:00:00+07:00 2025-01-02 06:00:00+07:00               5
3   2025-01-05 06:00:00+07:00 2025-01-05 12:00:00+07:00               6
4   2025-01-05 20:00:00+07:00 2025-01-06 11:00:00+07:00              15
..                        ...                       ...             ...
297 2025-12-21 20:00:00+07:00 2025-12-22 03:00:00+07:00               7
298 2025-12-23 03:00:00+07:00 2025-12-23 11:00:00+07:00               8
299 2025-12-28 10:00:00+07:00 2025-12-28 11:00:00+07:00               1
300 2025-12-28 20:00:00+07:00 2025-12-29 11:00:00+07:00              15
301 2025-12-31 20:00:00+07:00 2026-01-01 07:00:00+07:00              11

[302 rows x 3 columns]